### ISSUE TITLE
Need to remove matrix inversion in predication variance and standard errors

### ISSUE THREAD

**Issue by cjekel** [cjekel/piecewise_linear_fit_py#10]
It's not good practice to invert matrices. I need to rework the prediction variance and standard errors calculation such that the matrix inversion is not necessary. 

Is it possible to use a solver instead of matrix inversion?

This needs further investigation.

**Comment by V-Kh** [comment]
Hi
I see what you want to do. However, using your solution as it is now requires inverse matrices. 
I think that the only way is to use intermediate steps from that presentation (or find a more appropriate source) and find the answer step by step. Unfortunately, LibreOffice makes it partially unreadable. Could you provide a bit more details?

**Comment by cjekel** [comment]
Does this link work? https://uflorida-my.sharepoint.com/:p:/g/personal/cjekel_ufl_edu/EYjn0Akrd_1AqeZLQp6yWFUBv6bS1a0V6wtVTdN29A_vkQ?e=I81wdC

slide number 9 

I basically want to know if it's possible top get the prediction variance (or standard errors) without inv(X.T*X), or if there is a more efficient way to implement this in numpy?

I don't think we can use a linear matrix solver... but I'll have to investigate more

**Comment by V-Kh** [comment]
Yes, thanks, this one is much better. 
Is it possible to use a different version of that formula that is given by x^{(m)T} \sum_b x^{(m)}?
I didn't read this new code carefully, but you should have all this data (or be able to calculate it).

**Comment by cjekel** [comment]
The derivation of this type of Standard Error (or what I'm calling prediction variance) is in _Section 6.5.1 Standard Error of Predicted Response_ from [1] (and should be in the other editions). I can send a copy of this exert to you if you are interested.

Nice find about x^{(m)T} \sum_b x^{(m)}. I think this is a typo in the slide, but let me follow up with my supervisor. I'm unsure what \sum_b refers to.

[1] Myers, R. H., Montgomery, D. C., & Anderson-Cook, C. M. (2009). Building Empirical Models. In Response Surface Methodology: Process and Product Optimization Using Designed Experiments (Third, pp. 13–62). Wiley.

**Comment by cjekel** [comment]
The Sigma_b is actually the covariance matrix, thus it appears that the inversion is inevitable.

\Sigma_b = \cov (b) = \sigma^2 (X^T X)^{-1}
