### ISSUE TITLE
write paper describing all mathematical methods used in library

### ISSUE THREAD

**Issue by cjekel** [cjekel/piecewise_linear_fit_py#12]
This Library has grown significantly since it's inception. I've included statistical features that have not been formally written (standard errors and prediction variance). 

Before I fall behind, I need to write a paper describing all of the features and use cases of this library. This will need to describe the underlining mathematics and statistics the library follows.

**Comment by SebastianHD** [comment]
For now. What is the best way to reference your work?

**Comment by cjekel** [comment]
Thank you for wanting to cite this work. 

You can cite my work as 
```biblatex
@Manual{pwlf,
	author = {Jekel, Charles F. and Venter, Gerhard},
	title = {{pwlf:} A Python Library for Fitting 1D Continuous Piecewise Linear Functions},
	year = {2019},
	url = {https://github.com/cjekel/piecewise_linear_fit_py}
} 
```
Which will look something like the following when formatted.

C. F. Jekel and G. Venter, pwlf: A Python Library for Fitting 1D Continuous Piecewise Linear Functions, 2019. [Online]. Available: https://github.com/cjekel/piecewise_linear_fit_py

I've uploaded a draft version of the manuscript in the paper folder. You can download it [here](https://github.com/cjekel/piecewise_linear_fit_py/raw/master/paper/pwlf_Jekel_rev02_draft.pdf).

---

It will take a very long time before a peer reviewed manuscript comes out.

**Comment by cjekel** [comment]
Newer version of the paper is out. You can download the paper [here](https://github.com/cjekel/piecewise_linear_fit_py/raw/master/paper/pwlf_Jekel_Venter_v1.pdf).
