### ISSUE TITLE
Feature request: remove output messages, restricted result range

### ISSUE THREAD

**Issue by V-Kh** [cjekel/piecewise_linear_fit_py#3]
Hi again!

Sorry for disturbing, but I would like to ask you a few more things.
First, is it possible to add a key parameter which turns off _all_ the output messages (except errors)? 
I have to deal with massive numbers of files and I need to see my own print messages.

Second, can your algorithm in general use boundaries for resulting parameters? Say, I know in general, that the values of slopes _a priori_ lie in range [0:2], thus, the result has to be in the range.

Sincerely,
V.

**Comment by cjekel** [comment]
> First, is it possible to add a key parameter which turns off all the output messages (except errors)?
> I have to deal with massive numbers of files and I need to see my own print messages.

you can use something like
```
fit(4,disp=False)
```
to fit to four line segments while turning off the optimization output...

What is sometimes printed often are numpy warnings, i.e. divide by zero. You can look at https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings to disable  warnings in Python.

Does this help?

> Second, can your algorithm in general use boundaries for resulting parameters? Say, I know in general, that the values of slopes a priori lie in range [0:2], thus, the result has to be in the range.
The fit doesn't solve for the slopes, it actually solves for the y locations provided x break points. From this solution the slopes can be calculated.

I'm working on implementing fixing the x,y locations at the boundaries (beginning and end). There has been a few people who have requested this, but it's not ready (or working) at the moment.

**Comment by V-Kh** [comment]
> you can use something like
> 
> `fit(4,disp=False)`

No, I still get messages like 

`fun: 4.895025824377757e-07`
` message: 'Optimization terminated successfully.'`
`    nfev: 393`
`     nit: 12`
` success: True`
`       x: array([2.6693644 , 3.32241918])`
And when I try to use fitfast, it becomes even worse (especially with 4 cores running)
> What is sometimes printed often are numpy warnings, i.e. divide by zero. 

I observe some messages, indeed, they look like this:
```
RuntimeWarning: invalid value encountered in double_scalars
  A[i,i] = A[i,i] + sum(((sepDataX[i] - breaks[i+1]) ** 2)) / ((breaks[i+1] - breaks[i]) ** 2)
/home/user/.local/lib/python3.6/site-packages/pwlf/pwlf.py:248: RuntimeWarning: invalid value encountered in double_scalars
  A[i,i+1] = A[i,i+1] - sum((sepDataX[i] - breaks[i]) * (sepDataX[i] - breaks[i+1])) / ((breaks[i+1] - breaks[i]) ** 2)
/home/user/.local/lib/python3.6/site-packages/pwlf/pwlf.py:249: RuntimeWarning: invalid value encountered in double_scalars
  B[i] = B[i] + (-sum(sepDataX[i] * sepDataY[i]) + breaks[i+1] * sum(sepDataY[i])) / (breaks[i+1] - breaks[i])
/home/user/.local/lib/python3.6/site-packages/pwlf/pwlf.py:241: RuntimeWarning: invalid value encountered in double_scalars
  A[i,i-1] = A[i,i-1] - sum((sepDataX[i-1] - breaks[i-1]) * (sepDataX[i-1] - breaks[i])) / ((breaks[i] - breaks[i-1]) ** 2)
/home/user/.local/lib/python3.6/site-packages/pwlf/pwlf.py:242: RuntimeWarning: invalid value encountered in double_scalars
  A[i,i] = A[i,i] + sum((sepDataX[i-1] - breaks[i-1]) ** 2) / ((breaks[i] - breaks[i-1]) ** 2)
/home/user/.local/lib/python3.6/site-packages/pwlf/pwlf.py:243: RuntimeWarning: invalid value encountered in double_scalars
  B[i] = B[i] + (sum(sepDataX[i-1] * sepDataY[i-1]) - breaks[i-1] * sum(sepDataY[i-1])) / (breaks[i] - breaks[i-1])
```
and 
```
/home/user/.local/lib/python3.6/site-packages/numpy/core/_methods.py:112: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
```
Is that what you mean? 
> Would you like a keyword to turn this off?

Yes, that would be great. Since I can't be sure that results in such cases are correct, I need to know what datasets lead to this (and I have a few thousands =/).



> I'm working on implementing fixing the x,y locations at the boundaries (beginning and end). There has been a few people who have requested this, but it's not ready (or working) at the moment.

Well, that means that I have to do more things manually.

P.S.  It seems that your fitfast doesn't work as planned, however, I need to check, what data breaks it, and open a new issue.

**Comment by cjekel** [comment]
Thanks for the PR! 

1. https://github.com/cjekel/piecewise_linear_fit_py/commit/66c02453f4423656b71232d36b0f48fe9f59f8bd now defaults to prints being off. Use 
```
piecewise_lin_fit(x, y, disp_res=True)
```
to turn prints on. This doesn't get rid of numpy warnings.

2. https://github.com/cjekel/piecewise_linear_fit_py/commit/9959ec25ae71b824039d1ef5ff23d6c9ba5a44e7 fitfast() now defaults to a population of 2. This should be faster than the differential evolution for all cases, at the cost of possibly not finding a good solution. Increase the population of fitfast() to find a better solution. 

3. Can you describe you application for boundary slopes? Are you trying to force a solution range, or speed up the optimization implementation?

**Comment by V-Kh** [comment]
Good, now I can see only important messages!
I haven't tried to use updated fitfast yet, hope it works properly now. 
I know, that slopes can't be, say, negative and greater than 2. Thus, all values that are not in range can't be accepted. I know, that, for example, scipy allows to use boundaries for ranges, but your package is better for my purposes. 

P.S. Your updated version definitely looks faster, however, now I get very strange results. This drives me crazy %)
![msd_plot 6](https://user-images.githubusercontent.com/6596606/38817007-51cb2292-418f-11e8-9ebf-10a7095d1510.png)
![_msd_plot 0 1 3_0 22](https://user-images.githubusercontent.com/6596606/38817029-62958fb8-418f-11e8-93cd-ffed1f640ef2.png)
Same dataset (msd shifted), but correct (at least acceptable) results only in the case of old algo. I use default code from your examples and 3 segments to fit the data.

**Comment by cjekel** [comment]
Can you send me that msd shifted dataset to troubleshoot? Or reproduce on a simple data set? Are you using version 0.2.3? 

In the meantime you can revert to the old release by running
```bash
[sudo] pip uninstall pwlf
[sudo] pip install pwlf==0.1.7 
```

**Comment by cjekel** [comment]
Fixed the weird prediction issues in 0.2.4. Sorry about that, not sure how that escaped my test function! I need to think about that more...

> I know, that slopes can't be, say, negative and greater than 2. Thus, all values that are not in range can't be accepted. I know, that, for example, scipy allows to use boundaries for ranges, but your package is better for my purposes.


Okay. I need to think about this more, but I think it can be done by setting up inequality constraints. 

They would look something like
b_l <= b_1 <= b_h
Then
1 <= b_1/b_l
and
1 >= b_1/b_h

this might be useful for future https://math.stackexchange.com/questions/69613/linear-least-squares-with-inequality-constraints

**Comment by V-Kh** [comment]
> Okay. I need to think about this more, but I think it can be done by setting up inequality constraints.

Thank you.
The attached file is one of those with strange values. The first column contains time, the last one is the data I need. I import it, skip the first row with zero values and use numpy.log10() to linearize it. 

`data = pd.read_csv(file, sep='\s+', engine='python', usecols=(0, 3),  skiprows=1, names=('lag', 'msd_shift'))`
`lag = np.log10(data['lag'].as_matrix())`
`msd_shift = np.log10(data['msd_shift'].as_matrix())`

[data.zip](https://github.com/cjekel/piecewise_linear_fit_py/files/1916405/data.zip)

**Comment by cjekel** [comment]
Works good in version 0.2.4! 
![temp](https://user-images.githubusercontent.com/13884657/38825270-f85fd8d4-4179-11e8-999f-c24daaa70747.png)

```python
import numpy as np
import matplotlib.pyplot as plt
import pwlf
import pandas as pd
data = pd.read_csv('ref_msd.16.bin', sep='\s+', engine='python', usecols=(0, 3), skiprows=1, names=('lag', 'msd_shift'))
lag = np.log10(data['lag'].as_matrix())
msd_shift = np.log10(data['msd_shift'].as_matrix())
myPWLF = pwlf.PiecewiseLinFit(lag, msd_shift)
myPWLF.fit(3)
yhat = myPWLF.predict(lag)
plt.figure()
plt.plot(lag, msd_shift, 'o')
plt.plot(lag, yhat)
plt.show()

```

**Comment by V-Kh** [comment]
Great! 
However, could you please take a look at the values of slopes: they are a little bit strange: 
`myPWLF.slopes`
`array([ 1.89755427, -0.67540119,  2.00421613])`
