### ISSUE TITLE
Could I use just piecewise horizontal and vertical lines to fit datas ?

### ISSUE THREAD

**Issue by lk1983823** [cjekel/piecewise_linear_fit_py#31]
I want fit the data (yellow ones),using piecewise horizontal and vertical lines but failed. Could pwlf make it possible?
![微信截图_20190517220312](https://user-images.githubusercontent.com/20237650/57933610-4fee1d00-78f0-11e9-8f16-68d39bff58dd.png)

**Comment by cjekel** [comment]
What happens when you run fit(9) ?

**Comment by lk1983823** [comment]
Although it can fit the data using 10 piecewise, the lines are not strictly horizontal and vertical.

**Comment by lk1983823** [comment]
Below is a reslut using pwlf with fit(11). So I want to add contraints to pwlf to make sure the line be strictly horizontal or vertical.
![微信截图_20190518092257](https://user-images.githubusercontent.com/20237650/57962829-86f31b80-794e-11e9-9bd1-9bdd52429fa1.png)

**Comment by cjekel** [comment]
I'd be willing to collaborate on this if it will be useful and you can send
me an email with more details, but I probably won't include the
functionality in pwlf.

How many square waves do you expect? and will the data be periodic.
(Thousands of square waves of non periodic data may be challenging...)

**Comment by lk1983823** [comment]
I have send an email to you with data and code of my early work.

**Comment by cjekel** [comment]
For those interested, I have a development branch to include this functionality. https://github.com/cjekel/piecewise_linear_fit_py/tree/constants

I added a degree keyword which you can specify what degree piecewise polynomial to use.
```python
my_pwlf = pwlf.PiecewiseLinFit(x, y, degree=0)  # constants
my_pwlf = pwlf.PiecewiseLinFit(x, y, degree=1)  # linear (default)
my_pwlf = pwlf.PiecewiseLinFit(x, y, degree=2)  # quadratic
```

It needs more testing before being merged.

**Comment by lk1983823** [comment]
Thank you! I will try it.

**Comment by cjekel** [comment]
Let me keep this open for now. There are some issues with the implementation. (The number of parameters counts are incorrect for polynomials, no tests, etc.). I'll close this issue when it's been fully merged.
