### ISSUE TITLE
Proposal: non-array arguments to PiecewiseLinFit.predict()

### ISSUE THREAD

**Issue by kingrpaul** [cjekel/piecewise_linear_fit_py#32]
Calling predict() with a float type argument raises IndexError (vs TypeError). 

 ```
        if sorted_data is False:
            # sort the data from least x to max x
            order_arg = np.argsort(x)
            x = x[order_arg]  <<--- HERE
```
Consider detecting non-array arguments to predict?

**Comment by cjekel** [comment]
I just removed the sorted keywords in the 1.0.0 release ( at least I think
so).

You're right that checking for an array type would remove the error.

Is this sill an issue on 1.0.0?

**Comment by kingrpaul** [comment]
pip-installed yesterday
Version -> 0.5.1
Sounds like this will no longer be an issue, with update?

**Comment by cjekel** [comment]
Sorry I haven't tested this, but does 1.0.0 avoid this issue?
