### ISSUE TITLE
Small problem in documentation

### ISSUE THREAD

**Issue by xhain** [cjekel/piecewise_linear_fit_py#42]
Hey @cjekel ,

thank you for this library! It's been a great help in prototyping some ideas this week.
I found a slight mismatch in the documentation:

`PieceWiseLinFit.fitfast` and `PieceWiseLinFit.fit_guess` mention that `scipy.optimize.differential_evolution` is used, but that's not true. It's only called for `PieceWiseLinFit.fit`.

`PieceWiseLinFit.fitfast` and `PieceWiseLinFit.fit_guess` both use `scipy.optimize.fmin_l_bfgs_b` instead.

It's correct further down in the documentation (near the examples) though.

See:
https://github.com/cjekel/piecewise_linear_fit_py/blob/ad665460e8d3dc7fd8b1c751c1ddd70a3e4018f3/pwlf/pwlf.py#L1016

https://github.com/cjekel/piecewise_linear_fit_py/blob/ad665460e8d3dc7fd8b1c751c1ddd70a3e4018f3/pwlf/pwlf.py#L1165

**Comment by cjekel** [comment]
Nice catch! Thanks for pointing this out. Feel free to send a PR to fix these docstrings that you pointed out.

**Comment by xhain** [comment]
Done!
