### ISSUE TITLE
Standard error of slopes and intercepts

### ISSUE THREAD

**Issue by azim7091** [cjekel/piecewise_linear_fit_py#63]
Hi,

How can I find the error of intercepts and slopes? is there such possibility in the code?

Thanks in Advance
Az

**Comment by azim7091** [comment]
sorry, I found out the answer. slope and intercept errors cab be derived by beta errors.

Thank you
Az

**Comment by vkhodygo** [comment]
@azim7091  you should close this issue as resolved.

**Comment by cjekel** [comment]
https://github.com/cjekel/piecewise_linear_fit_py/tree/master/examples#non-linear-standard-errors-and-p-values

@azim7091 Feel free to reach out if you have any questions on the format. I was thinking today that it is technically possible to propagate standard errors in beta parameters to slope-intercept form, although there may be some unintended consequences of doing so.
