### ISSUE TITLE
TypeError: scipy/linalg/interface.py

### ISSUE THREAD

**Issue by solomonvimal** [cjekel/piecewise_linear_fit_py#65]
I'm getting an error if I use the fit function for the standard example. I'm using Python3.6 and scipy version 1.1.0. 

```
my_pwlf = pwlf.PiecewiseLinFit(x, y)
res = my_pwlf.fit(2)
```
The error message is:
`
  File "/home/svimal/miniconda3/lib/python3.6/site-packages/scipy/optimize/lbfgsb.py", line 378, in _minimize_lbfgsb
    hess_inv = LbfgsInvHessProduct(s[:n_corrs], y[:n_corrs])
  File "/home/svimal/miniconda3/lib/python3.6/site-packages/scipy/sparse/linalg/interface.py", line 144, in __new__
    obj = super(LinearOperator, cls).__new__(cls)

TypeError: super(type, obj): obj must be an instance or subtype of type`

**Comment by cjekel** [comment]
Does this happen for any x and y data? If so it might be a problem with the lbfgsb in your scipy version.

Can you update scipy to version 1.2.0 and report back?

**Comment by solomonvimal** [comment]
@cjekel: Thanks! Yes, updating scipy (from 1.1.0 to 1.4.1) fixed the issue.
