### ISSUE TITLE
Can not run fitForSpecifiedNumberOfLineSegments.py

### ISSUE THREAD

**Issue by stadtwerker** [cjekel/piecewise_linear_fit_py#7]
Hi, 
I got some problems to run your fitForSpecifiedNumberOfLineSegments.py. I get the following error message: 

![unbenannt](https://user-images.githubusercontent.com/38392792/39620595-4395f70c-4f7b-11e8-907b-19d07ccf9347.PNG)

Can you help me, please?
My numpy version is 1.13.3 and scipy version is 1.0.0.

Sincerely, 
s.

**Comment by V-Kh** [comment]
Hi
Could you please provide a minimal working example of your code (and data as well).
Also, this package has certain [requirements](https://github.com/cjekel/piecewise_linear_fit_py#requirements). Try to update your packages first.
V.

**Comment by cjekel** [comment]
fitForSpecifiedNumberOfLineSegments.py works on my system. Make sure you are running the latest version of pwlf. I pushed versions to pypi that broke functionality. 

You can run the following to check your pwlf version.
```Python
import pwlf
print(pwlf.__version__)
```

Upgrading pwlf with
```
pip install pwlf --upgrade
```
Note this will try to upgrade numpy and scipy with pip. If you can't do that on your system run
```
pip install pwlf==0.2.5 
```

**Comment by stadtwerker** [comment]
Hi,
thanks for your responses. I think I got the latest version. I just made a copy of your code from GitHub, pasted it into my site packages (until now I never used pip to install or upgrade packages, because the access is restricted by my company) and ran the example above. 
What did I do wrong?
s.

**Comment by stadtwerker** [comment]
Hi,
I reinstalled pwlf using pip and it seems to work. Thanks!
s.
