### ISSUE TITLE
divide by zero error in calc slopes if two break points are the same, or if a breakpoint is on the boundary

### ISSUE THREAD

**Issue by cjekel** [cjekel/piecewise_linear_fit_py#91]
A user reported an issue where there is a divide by zero error when running `calc_slopes` once a breakpoint have been place on the boundary, or if two breakpoints are the exact same.

We can probably catch the exception and print a warning that `calc_slopes` encountered a divide by zero. This would preserve the api.

**Comment by rydtran** [comment]
Any updates on this bug fix?

**Comment by cjekel** [comment]
It looks like this is a numpy runtimewarning.
```python
pwlf.py:1109: RuntimeWarning: invalid value encountered in double_scalars
```
and should be safe to ignore if this is happening during a `.fit()`, `.fitfast(),` or `.fit_guess()` routine. These methods have a tendency to try two breakpoints at a boundary which cause a numpy divide by zero warning during a `.calc_slopes` call. This warning does not stop or interfere with the parameter fits.

You should take this warning that something is wrong if it happens when performing a `.fit_with_breaks()` call from one of the above solutions (or your own breakpoints).

In order to fix this, I need to add some flag to ensure that the `calc_slopes` method does not get called from within an optimization routine.
